NODE_TOKEN_DEFAULT="node_secret"
#!/usr/bin/env bash
set -euo pipefail

# Custom Hosting Panel Installer (Ubuntu)
# - Installs docker + compose plugin (apt)
# - Lets you choose HTTP or HTTPS (Let's Encrypt)
# - Lets you choose Panel or Node install (docker compose profiles)
# - Lets you set a panel name (NEXT_PUBLIC_PANEL_NAME)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

say() { echo -e "
[1m$*[0m" >&2; }
ask() { read -r -p "$1" REPLY; echo "$REPLY"; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    say "Please run as root (use sudo)"
    exit 1
  fi
}

install_deps() {
  say "Installing dependencies (git, curl, ca-certificates)..."
  apt-get update -y
  apt-get install -y git curl ca-certificates gnupg lsb-release
}

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    say "Docker already installed."
    return
  fi
  say "Installing Docker (official repo)..."
  install_deps

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  UBUNTU_CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    ${UBUNTU_CODENAME} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
}

write_env() {
  local panel_name="$1"
  cat > .env <<EOF
# Generated by scripts/install.sh
NEXT_PUBLIC_PANEL_NAME=${panel_name}
NEXT_PUBLIC_API_URL=/api
DOMAIN=${DOMAIN:-}
NODE_TOKEN=${NODE_TOKEN_DEFAULT}
EOF
}

choose_panel_name() {
  say "Panel name"
  local yn
  yn="$(ask "Do you want to set a custom panel name? (y/n) ")"
  if [[ "$yn" =~ ^[Yy]$ ]]; then
    local name
    name="$(ask "Enter panel name: ")"
    if [[ -z "$name" ]]; then
      echo "Custom Hosting Panel"
    else
      echo "$name"
    fi
  else
    echo "Custom Hosting Panel"
  fi
}

choose_http_https() {
  say "HTTP or HTTPS"
  local choice
  choice="$(ask "Use HTTPS with a domain? (https/http) [http]: ")"
  if [[ -z "$choice" ]]; then choice="http"; fi
  echo "$choice"
}

setup_https() {
  say "HTTPS setup (Let's Encrypt)"
  DOMAIN="$(ask "Enter your domain (example: panel.example.com): ")"
  if [[ -z "$DOMAIN" ]]; then
    echo "Domain required for HTTPS."
    exit 1
  fi
  EMAIL="$(ask "Enter email for Let's Encrypt (recommended): ")"
  if [[ -z "$EMAIL" ]]; then
    EMAIL="admin@${DOMAIN}"
  fi

  apt-get update -y
  apt-get install -y certbot

  # Stop panel nginx if it's already bound to 80/443
  docker compose --profile panel down >/dev/null 2>&1 || true

  say "Requesting certificate for ${DOMAIN} (standalone on port 80)..."
  certbot certonly --standalone -d "${DOMAIN}" -m "${EMAIL}" --agree-tos --non-interactive --keep-until-expiring

  say "Configuring nginx for HTTPS..."
  export DOMAIN
  envsubst '${DOMAIN}' < nginx/conf.d/https.conf.template > nginx/conf.d/default.conf
}

setup_http() {
  say "Configuring nginx for HTTP..."
  cp -f nginx/conf.d/http.conf.template nginx/conf.d/default.conf
}

choose_role() {
  say "Install role"
  local role
  role="$(ask "Are you installing the PANEL, the NODE, or BOTH on this VPS? (panel/node/both) [both]: ")"
  if [[ -z "$role" ]]; then role="both"; fi
  echo "$role"
}

start_services() {
  local role="$1"
  if [[ "$role" == "panel" ]]; then
    say "Starting PANEL services (web/api/nginx/postgres/redis)..."
    docker compose --profile panel up -d --build
    say "Done. Open:"
    if [[ "${USE_HTTPS}" == "https" ]]; then
      echo "  https://${DOMAIN}"
    else
      echo "  http://<YOUR_SERVER_IP>/login"
    fi
    echo "Default admin login: admin / admin"
  elif [[ "$role" == "node" ]]; then
    say "Starting NODE daemon service..."
    docker compose --profile node up -d --build
    say "Done. Node daemon is listening on port 5000."
    echo "Add this node in the PANEL admin:"
    echo "  URL: http://<NODE_IP>:5000"
    echo "  Token: node_secret"
  else
    say "Starting BOTH PANEL + NODE services..."
    docker compose --profile panel --profile node up -d --build
    say "Done. Open:"
    if [[ "${USE_HTTPS}" == "https" ]]; then
      echo "  https://${DOMAIN}"
    else
      echo "  http://<YOUR_SERVER_IP>/login"
    fi
    echo "Default admin login: admin / admin"
    echo ""
    echo "Node daemon is running too (port 5000). Add it in Admin → Nodes:"
    echo "  URL: http://<THIS_SERVER_IP>:5000"
    echo "  Token: node_secret"
  fi
}

main() {
  require_root
  install_docker

  PANEL_NAME="$(choose_panel_name)"
  write_env "$PANEL_NAME"

  ROLE="$(choose_role)"

  USE_HTTPS="http"
  if [[ "$ROLE" == "panel" || "$ROLE" == "both" ]]; then
    USE_HTTPS="$(choose_http_https)"
    if [[ "$USE_HTTPS" == "https" ]]; then
      setup_https
    else
      setup_http
    fi
  fi

  start_services "$ROLE"
}

main "$@"
